app/classes/item/__init__.py
from flask import Blueprint

item = Blueprint('item', __name__)

from .import views

app/classes/item/views.py
from flask import flash, redirect, render_template, url_for

from . import item
from .form import CreateAnItemForm
from ... import db
# from .Item import Item
from ...models import Item


@item.route('/items', methods=['GET', 'POST'])
def list_items():
    items = Item.query.all()
    return render_template('list_pages/items.html',
                           items=items, title="Items")


@item.route('/items/edit/<int:item_id>', methods=['GET', 'POST'])
def edit(item_id):
    add_item = False
    edit_item = Item.query.get_or_404(item_id)
    form = CreateAnItemForm(obj=item)
    if form.validate_on_submit():
        edit_item.name = form.name.data
        edit_item.type_category = form.type_category.data
        edit_item.kosher_category = form.kosher_category.data
        edit_item.expiration_date = form.expiration_date.data
        edit_item.place_taken = form.place_taken.data
        db.session.commit()
        flash('You have successfully edited the item.')

        return redirect(url_for('item.list_items'))

    form.name.data = edit_item.name
    form.type_category.data = edit_item.type_category
    form.kosher_category.data = edit_item.kosher_category
    form.expiration_date.data = edit_item.expiration_date
    form.place_taken.data = edit_item.place_taken

    return render_template('edit/item.html', action="Edit",
                           add_item=add_item, form=form,
                           item=edit_item, title="Edit Item")


@item.route('/items/add', methods=['GET', 'POST'])
def add():
    add_item = True
    form = CreateAnItemForm()
    if form.validate_on_submit():
        new_item = Item(name=form.name.data,
                        type_category=form.type_category.data,
                        kosher_category=form.kosher_category.data,
                        expiration_date=form.expiration_date.data,
                        place_taken=form.place_taken.data)

        try:
            db.session.add(new_item)
            db.session.commit()
            flash('You have successfully added a new shelf.')
        except:
            flash('Error: shelf name already exists.')

        return redirect(url_for('item.list_items'))

    return render_template('edit/item.html', add_item=add_item,
                           form=form, title='Add Item')


@item.route('/departments/delete/<int:item_id>', methods=['GET', 'POST'])
def delete(item_id):
    delete_item = Item.query.get_or_404(item_id)
    db.session.delete(delete_item)
    db.session.commit()
    flash('You have successfully deleted the item.')
    return redirect(url_for('item.list_items'))

app/classes/refrigerator/__init__.py
from flask import Blueprint

refrigerator = Blueprint('refrigerator', __name__)

from . import views

app/classes/refrigerator/views.py
from flask import flash, redirect, render_template, url_for

from . import refrigerator
from .form import CreateARefrigeratorForm
from ... import db
# from .refrigerator import Refrigerator
from ...models import Refrigerator


@refrigerator.route('/refrigerators')
def list_refrigerators():
    refrigerators = Refrigerator.query.all()
    return render_template('list_pages/refrigerators.html',
                           refrigerators=refrigerators, title='Refrigerators')


@refrigerator.route('/refrigerators/add', methods=['GET', 'POST'])
def add():
    add_refrigerator = True

    form = CreateARefrigeratorForm()
    if form.validate_on_submit():
        new_refrigerator = Refrigerator(model=form.model.data,
                                        color=form.color.data)
        try:
            # add role to the database
            db.session.add(new_refrigerator)
            db.session.commit()
            flash('You have successfully added a new refrigerator.')
        except:
            flash('Error: refrigerator name already exists.')

        return redirect(url_for('refrigerator.list_refrigerators'))
    return render_template('edit/refrigerator.html', add_refrigerator=add_refrigerator,
                           form=form, title='Add Refrigerator')


@refrigerator.route('/refrigerators/edit/<int:refrigerator_id>', methods=['GET', 'POST'])
def edit(refrigerator_id):
    add_refrigerator = False

    edit_refrigerator = Refrigerator.query.get_or_404(refrigerator_id)
    form = CreateARefrigeratorForm(obj=edit_refrigerator)
    if form.validate_on_submit():
        edit_refrigerator.model = form.model.data
        edit_refrigerator.color = form.color.data
        db.session.add(edit_refrigerator)
        db.session.commit()
        flash('You have successfully edited the refrigerator.')

        return redirect(url_for('refrigerator.list_refrigerators'))

    form.model.data = edit_refrigerator.model
    form.color.data = edit_refrigerator.color
    return render_template('edit/refrigerator.html', add_refrigerator=add_refrigerator,
                           form=form, title="Edit Refrigerator")


@refrigerator.route('/refrigerators/delete/<int:refrigerator_id>', methods=['GET', 'POST'])
def delete(refrigerator_id):
    delete_refrigerator = Refrigerator.query.get_or_404(refrigerator_id)
    db.session.delete(delete_refrigerator)
    db.session.commit()
    flash('You have successfully deleted the refrigerator.')

    return redirect(url_for('refrigerator.list_refrigerators'))

app/templates/list_pages/compare_methods.html
{% import "bootstrap/wtf.html" as wtf %}
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Methods{% endblock %}
{% block body %}
<div class="content-section">
    <div class="outer">
        <div class="middle">
            <div class="inner">
                <br/>
                {{ utils.flashed_messages() }}
                <br/>
                <h1 style="text-align:center;">Comparing Methods</h1>
                <hr class="intro-divider">
                <div class="center">
                    <table class="table table-striped table-bordered">
                        <thead>
                        <tr>
                            <th width="20%"> Name</th>
                            <th width="40%"> Description</th>
                            <th width="40%"> Fill the template</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>Compare refrigerators</td>
                            <td>Compare between 2 refrigerators</td>
                            <td>
                                {% if template %}
                                {{ wtf.quick_form(refrigerator_form) }}
                                {% endif %}
                            </td>
                        </tr>
                        <tr>
                            <td>Compare shelves</td>
                            <td>Compare between 2 shelves</td>
                            <td>
                                {% if template %}
                                {{ wtf.quick_form(shelf_form) }}
                                {% endif %}
                            </td>
                        </tr>
                        <tr>
                            <td>Compare items</td>
                            <td>Compare between 2 items</td>
                            <td>
                                {% if template %}
                                {{ wtf.quick_form(item_form) }}
                                {% endif %}
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div style="text-align: center">
                    <div style="text-align: center">
                        <hr class="intro-divider">
                        <a href="{{ url_for('methods.list_methods') }}" class="btn btn-default btn-lg">
                            <i class="fa fa-plus"></i>
                            Go back
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/list_pages/items.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Items{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Items</h1>
        {% if items %}
          <hr class="intro-divider">
          <div class="center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th width="15%"> Name </th>
                  <th width="40%"> Description </th>
                  <th width="15%"> Edit </th>
                  <th width="15%"> Delete </th>
                </tr>
              </thead>
              <tbody>
              {% for item in items %}
                <tr>
                  <td> {{ item.name }} </td>
                  <td> {{ item.kosher_category }} </td>
                  <td>
                      <a href="{{ url_for('item.edit', item_id=item.id) }}">
                      <i class="fa fa-pencil"></i> Edit 
                    </a>
                  </td>
                  <td>
                     <a href="{{ url_for('item.delete', item_id=item.id) }}">
                      <i class="fa fa-trash"></i> Delete 
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
      </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> No items have been added. </h3>
            <hr class="intro-divider">
        {% endif %}
          <a href="{{ url_for('item.add') }}" class="btn btn-default btn-lg">
            <i class="fa fa-plus"></i>
            Add Item
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/list_pages/methods.html
{% import "bootstrap/wtf.html" as wtf %}
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Methods{% endblock %}
{% block body %}
<div class="content-section">
    <div class="outer">
        <div class="middle">
            <div class="inner">
                <br/>
                {{ utils.flashed_messages() }}
                <br/>
                <h1 style="text-align:center;">Methods Menu</h1>
                <hr class="intro-divider">
                <div class="center">
                    <table class="table table-striped table-bordered">
                        <thead>
                        <tr>
                            <th width="20%"> Name</th>
                            <th width="40%"> Description</th>
                            <th width="40%"> Navigate to methods</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>Comparing objects</td>
                            <td>Compare between 2 of the same object</td>
                            <td>
                                <a href="{{ url_for('methods.compare_methods') }}">link</a>
                            </td>
                        </tr>
                        <tr>
                            <td>Compare shelves</td>
                            <td>Compare between 2 shelves</td>
                            <td>
                                {% if template %}
                                link
                                {% endif %}
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/list_pages/objects_methods.html
{% import "bootstrap/wtf.html" as wtf %}
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Methods{% endblock %}
{% block body %}
<div class="content-section">
    <div class="outer">
        <div class="middle">
            <div class="inner">
                <br/>
                {{ utils.flashed_messages() }}
                <br/>
                <h1 style="text-align:center;">Object Methods</h1>
                <hr class="intro-divider">
                <div class="center">
                    <table class="table table-striped table-bordered">
                        <thead>
                        <tr>
                            <th width="20%"> Name</th>
                            <th width="40%"> Description</th>
                            <th width="40%"> Fill the template</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>Insert an item</td>
                            <td>Choose a refrigerator, and an item you wish to insert to the refrigerator</td>
                            <td>
                                {% if template %}
                                {{ wtf.quick_form(add_item) }}
                                {% endif %}
                            </td>
                        </tr>
                        <tr>
                            <td>Take an item out</td>
                            <td>Choose a refrigerator, and an item you wish to remove from the refrigerator</td>
                            <td>
                                {% if template %}
                                {{ wtf.quick_form(take_out) }}
                                {% endif %}
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div style="text-align: center">
                    <div style="text-align: center">
                        <hr class="intro-divider">
                        <a href="{{ url_for('methods.list_methods') }}" class="btn btn-default btn-lg">
                            <i class="fa fa-plus"></i>
                            Go back
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/list_pages/refrigerator_methods.html
{% import "bootstrap/wtf.html" as wtf %}
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Methods{% endblock %}
{% block body %}
<div class="content-section">
    <div class="outer">
        <div class="middle">
            <div class="inner">
                <br/>
                {{ utils.flashed_messages() }}
                <br/>
                <h1 style="text-align:center;">Refrigerator Methods</h1>
                <hr class="intro-divider">
                <div class="center">
                    <table class="table table-striped table-bordered">
                        <thead>
                        <tr>
                            <th width="20%"> Name</th>
                            <th width="40%"> Description</th>
                            <th width="40%"> Fill the template</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>Cleanup refrigerator</td>
                            <td>Remove all expired items</td>
                            <td>
                                {{ wtf.quick_form(cleanup) }}
                            </td>
                        </tr>
                        <tr>
                            <td>Whats to eat</td>
                            <td>Compare between 2 shelves</td>
                            <td>
                                {{ wtf.quick_form(more) }}
                            </td>
                        </tr>
                        <tr>
                            <td>Getting shopping ready</td>
                            <td>Compare between 2 items</td>
                            <td>
                                {{ wtf.quick_form(last) }}
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div style="text-align: center">
                    <div style="text-align: center">
                        <hr class="intro-divider">
                        <a href="{{ url_for('methods.list_methods') }}" class="btn btn-default btn-lg">
                            <i class="fa fa-plus"></i>
                            Go back
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/list_pages/refrigerators.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Refrigerators{% endblock %}
{% block body %}
<div class="content-section">
    <div class="outer">
        <div class="middle">
            <div class="inner">
                <br/>
                {{ utils.flashed_messages() }}
                <br/>
                <h1 style="text-align:center;">Refrigerators</h1>
                {% if refrigerators %}
                <hr class="intro-divider">
                <div class="center">
                    <table class="table table-striped table-bordered">
                        <thead>
                        <tr>
                            <th width="15%"> Name</th>
                            <th width="40%"> Description</th>
                            <th width="15%"> Stored shelves</th>
                            <th width="15%"> Edit</th>
                            <th width="15%"> Delete</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for refrigerator in refrigerators %}
                        <tr>
                            <td> {{ refrigerator.model }}</td>
                            <td> {{ refrigerator.color }}</td>
                            <td>
                                {% if refrigerator.shelves_list %}
                                {% for shelf in refrigerator.shelves_list %}
                                shelf.level_number: {{shelf.level_number}}
                                {% endfor %}
                                {% else %}
                                0
                                {% endif %}
                            </td>
                            <td>
                                <a href="{{ url_for('refrigerator.edit', refrigerator_id=refrigerator.id) }}">
                                    <i class="fa fa-pencil"></i> Edit
                                </a>
                            </td>
                            <td>
                                <a href="{{ url_for('refrigerator.delete', refrigerator_id=refrigerator.id) }}">
                                    <i class="fa fa-trash"></i> Delete
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div style="text-align: center">
                    {% else %}
                    <div style="text-align: center">
                        <h3> No Refrigerators have been added. </h3>
                        <hr class="intro-divider">
                        {% endif %}
                        <a href="{{ url_for('refrigerator.add') }}" class="btn btn-default btn-lg">
                            <i class="fa fa-plus"></i>
                            Add Refrigerator
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/list_pages/shelves.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Refrigerators{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Shelves</h1>
        {% if shelves %}
          <hr class="intro-divider">
          <div class="center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th width="15%"> Level_number </th>
                  <th width="15%"> Stored items </th>
                  <th width="15%"> Edit </th>
                  <th width="15%"> Delete </th>
                </tr>
              </thead>
              <tbody>
              {% for shelf in shelves %}
                <tr>
                  <td> {{ shelf.level_number }} </td>
                  <td>
                    {% if shelf.items_list %}
                    {% for item in shelf.items_list %}
                          {{ item.name }}
                    {% endfor %}
                    {% else %}
                      0
                    {% endif %}
                  </td>
                  <td>
                    <a href="{{ url_for('shelf.edit', shelf_id=shelf.id) }}">
                      <i class="fa fa-pencil"></i> Edit 
                    </a>
                  </td>
                  <td>
                    <a href="{{ url_for('shelf.delete', shelf_id=shelf.id) }}">
                      <i class="fa fa-trash"></i> Delete 
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> No Shelves have been added. </h3>
            <hr class="intro-divider">
        {% endif %}
          <a href="{{ url_for('shelf.add') }}" class="btn btn-default btn-lg">
            <i class="fa fa-plus"></i>
            Add Shelf
          </a>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}